# -*- coding: utf-8 -*-
"""LR_v3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HhAt2xzA4sHlOSJZ-3JUWHc_6J-isflG

    Two separate files are needed.
        - One being the file containing basic stock information (ticker, change percentage, date)
        - Another one contains specific factors for each stock.
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import math
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_squared_error

df = pd.read_csv('happyworking.csv')
df['orig_ticker'] = df['ticker']
df['ticker'] = df['ticker'].astype('category').cat.codes
df['exchangeCD'] = df['exchangeCD'].astype('category').cat.codes

lists = list(df['tradeDate'])
new_list=[]
for i in lists:
  new_list.append(i.replace('-',''))
df['tradeDate'] = new_list
df['tradeDate'] = df['tradeDate'].astype(np.int32)


train_begin_date = 20160100
train_end_date = 20190100
test_begin_date = 20190100
test_end_date = 20190200
result = pd.DataFrame(columns=['ticker','date','label','pred'])

for i in range(0,6):

    train = df[(df['tradeDate'] < train_end_date) & (df['tradeDate'] > train_begin_date)]
    test = df[(test_begin_date < df['tradeDate']) & (test_end_date > df['tradeDate'])]

    y_train = train[['label']]
    train = train.drop('label', axis=1)
    X_train = train.drop('tradeDate', axis=1)
    X_train = X_train.drop('orig_ticker',axis=1)

    temp = pd.DataFrame({'ticker': test['orig_ticker'], 'date': test['tradeDate'], 'label': test['label']})

    test = test.drop('label', axis=1)
    X_test = test.drop('tradeDate', axis=1)
    X_test = X_test.drop('orig_ticker', axis=1)
    test = test.drop('orig_ticker', axis=1)

    # Make some interactions
    poly = PolynomialFeatures(interaction_only=True,include_bias = False)
    poly.fit_transform(X_train)

    # Normalization
    regression_model = LinearRegression(normalize=True)
    regression_model.fit(X_train, y_train)

    for idx, col_name in enumerate(X_train.columns):
        print("The coefficient for {} is {}".format(col_name, regression_model.coef_[0][idx]))

    intercept = regression_model.intercept_[0]

    print("The intercept for our model is " + str(intercept))
    print('------------------------------------------------------------------------------------------------')

    #regression_model.score(X_test, y_test)

    sub_pred = regression_model.predict(X_test)
    temp_subpred = []
    for k in sub_pred:
        temp_subpred.append(k[0])
    temp['pred'] = temp_subpred

    # Month increment by 1
    train_begin_date += 100
    train_end_date += 100
    test_begin_date += 100
    test_end_date += 100

    result = result.append(temp, ignore_index = True)
regression_model_mse = mean_squared_error(result['pred'], result['label'])

mse = regression_model_mse

print('MSE: ', mse)

mpg = math.sqrt(regression_model_mse)
print('MPG: ',mpg)

# Uncomment to save the result
#result.to_csv('gundong_LR_result.csv', index=False)
df = result

df2 = pd.read_csv('real500.csv')
invest_total = 10000000
rank_interval = 100
zhongzheng_inverval = 500
dates = ['20190102','20190201','20190301','20190401','20190506','20190603']

lists = list(df2['monthBeginDate'])
new_list = []
for i in lists:
    new_list.append(i.replace('-',''))
df2['monthBeginDate'] = new_list
df2['monthBeginDate'] = df2['monthBeginDate'].astype(np.int32)

top = []
real500 = []
least = []

top_2 = []
real500_2 = []
least_2 = []

for day in dates:
    temp = (df.loc[df['date'] == (int(day) or str(day))])
    temp2 = (df2.loc[df2['monthBeginDate'] == (int(day) or str(day))])
    top100 = temp.nlargest(rank_interval, 'pred')
    last100 = temp.nsmallest(rank_interval, 'pred')

    top100_tickers = temp2.loc[temp2['ticker'].isin(top100['ticker'])]
    last100_tickers = temp2.loc[temp2['ticker'].isin(last100['ticker'])]

    real_profit = temp2['chgPct'].sum()
    pre_profit_top = top100_tickers['chgPct'].sum()
    pre_profit_last = last100_tickers['chgPct'].sum()

    # Discrete investment
    top.append(pre_profit_top*(invest_total/rank_interval)+invest_total)
    real500.append(real_profit*(invest_total/zhongzheng_inverval)+invest_total)
    least.append(pre_profit_last*(invest_total/rank_interval)+invest_total)

    # Accummulative investment
    if len(top_2) == 0:
        top_2.append(invest_total*(pre_profit_top/rank_interval+1))
        real500_2.append(invest_total*(real_profit/zhongzheng_inverval+1))
        least_2.append(invest_total*(pre_profit_last/rank_interval+1))
    else:
        top_2.append(top_2[-1]*(pre_profit_top/rank_interval+1))
        real500_2.append(real500_2[-1]*(real_profit/zhongzheng_inverval+1))
        least_2.append(least_2[-1]*(pre_profit_last/rank_interval+1))
print('Subgraph 1 data:')
print(top)
print(real500)
print(least)
print('\n')
print('Subgraph 2 data:')
print(top_2)
print(real500_2)
print(least_2)

# Back test plot
fig, (ax1, ax2) = plt.subplots(2, 1)
fig.suptitle('Back Test Based on LR with MSE = '+str(mse))
l1 = ax1.plot(dates, top, 'r')
l2 = ax1.plot(dates, real500, 'b')
l3 = ax1.plot(dates, least, 'g')
plt.ylabel('Discrete')
l4 = ax2.plot(dates, top_2, 'r')
l5 = ax2.plot(dates, real500_2, 'b')
l6 = ax2.plot(dates, least_2, 'g')

# Create the legend
fig.legend([l1, l2, l3],     # The line objects
           labels=['Top100', 'zhongzheng500', 'last100'],   # The labels for each line
           loc="center right",   # Position of legend
           borderaxespad=0.1,    # Small spacing around legend box
           #title="Legend Title"  # Title for the legend
           )
ax1.set_ylabel('Discrete Total')
ax2.set_ylabel('Accumulative Total')
plt.xlabel('Time (month)')
plt.show()
