# -*- coding: utf-8 -*-
"""LR_v2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HhAt2xzA4sHlOSJZ-3JUWHc_6J-isflG
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


df = pd.read_csv('0708.csv')
df = df[~(df == 0).any(axis=1)]

df['orig_ticker'] = df['ticker']
df['ticker'] = df['ticker'].astype('category').cat.codes

lists = list(df['tradeDate'])
new_list=[]
for i in lists:
  new_list.append(i.replace('-',''))
df['tradeDate'] = new_list
df['tradeDate'] = df['tradeDate'].astype(np.int32)


train = df[df['tradeDate']<20190000]
test = df[20190000<df['tradeDate']]

y_train = train[['label']]
train = train.drop('label', axis=1)
X_train = train.drop('tradeDate', axis=1)


y_test = test[['label']]
test = test.drop('label', axis=1)
X_test = test.drop('tradeDate', axis=1)

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

poly = PolynomialFeatures(interaction_only=True,include_bias = False)
poly.fit_transform(X_train)

regression_model = LinearRegression(normalize=True)
regression_model.fit(X_train, y_train)

for idx, col_name in enumerate(X_train.columns):
    print("The coefficient for {} is {}".format(col_name, regression_model.coef_[0][idx]))

intercept = regression_model.intercept_[0]

print("The intercept for our model is " + str(intercept))

#regression_model.score(X_test, y_test)

from sklearn.metrics import mean_squared_error

y_predict = regression_model.predict(X_test)

regression_model_mse = mean_squared_error(y_predict, y_test)

mse = regression_model_mse

print('MSE: ', mse)

import math
mpg = math.sqrt(regression_model_mse)
print('MPG: ',mpg)






lists = []
for i in list(y_predict):
  lists.append(i[0])
df = pd.DataFrame({'ticker':test['orig_ticker'],'date':test['tradeDate'],'pred':lists})
df.to_csv('gundong_LR_result')
def draw():
    df2 = pd.read_csv('real500.csv')
    invest_total = 10000000
    rank_interval = 100
    zhongzheng_inverval = 500
    dates = ['20190102','20190201','20190301','20190401','20190506','20190603']

    lists = list(df2['monthBeginDate'])
    new_list = []
    for i in lists:
        new_list.append(i.replace('-',''))
    df2['monthBeginDate'] = new_list
    df2['monthBeginDate'] = df2['monthBeginDate'].astype(np.int32)

    top = []
    real500 = []
    least = []

    top_2 = []
    real500_2 = []
    least_2 = []

    for day in dates:
        temp = (df.loc[df['date'] == (int(day) or str(day))])
        temp2 = (df2.loc[df2['monthBeginDate'] == (int(day) or str(day))])
        top100 = temp.nlargest(rank_interval, 'pred')
        last100 = temp.nsmallest(rank_interval, 'pred')

        top100_tickers = temp2.loc[temp2['ticker'].isin(top100['ticker'])]
        last100_tickers = temp2.loc[temp2['ticker'].isin(last100['ticker'])]

        real_profit = temp2['chgPct'].sum()
        pre_profit_top = top100_tickers['chgPct'].sum()
        pre_profit_last = last100_tickers['chgPct'].sum()

        # Discrete
        top.append(pre_profit_top*(invest_total/rank_interval)+invest_total)
        real500.append(real_profit*(invest_total/zhongzheng_inverval)+invest_total)
        least.append(pre_profit_last*(invest_total/rank_interval)+invest_total)

        # Accummulative
        if len(top_2) == 0:
            top_2.append(invest_total)
            real500_2.append(invest_total)
            least_2.append(invest_total)
        else:
            top_2.append(top_2[-1]*(pre_profit_top/rank_interval))
            real500_2.append(real500_2[-1]*(real_profit/zhongzheng_inverval))
            least_2.append(least_2[-1]*(pre_profit_last/rank_interval))
    top_2[0] = 0
    real500_2[0] = 0
    least_2[0] = 0


    # Plot
    fig, (ax1, ax2) = plt.subplots(2, 1)
    fig.suptitle('Back Test Based on LR with MSE = '+str(mse))
    l1 = ax1.plot(dates, top, 'r')
    l2 = ax1.plot(dates, real500, 'b')
    l3 = ax1.plot(dates, least, 'g')
    plt.ylabel('Discrete')

    l4 = ax2.plot(dates, top_2, 'r')
    l5 = ax2.plot(dates, real500_2, 'b')
    l6 = ax2.plot(dates, least_2, 'g')

    # Create the legend
    fig.legend([l1, l2, l3],     # The line objects
               labels=['Top100', 'zhongzheng500', 'last100'],   # The labels for each line
               loc="center right",   # Position of legend
               borderaxespad=0.1,    # Small spacing around legend box
               #title="Legend Title"  # Title for the legend
               )
    ax1.set_ylabel('discrete')
    ax2.set_ylabel('accumulative revenue')
    plt.xlabel('time (month)')
    plt.show()

draw()


